AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  Calcformathpanel:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: test.my_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 720
      Role: >-
        arn:aws:iam::160172051353:role/service-role/Calc_for_mathpanel-role-hdtzi6du
      Layers:
        - >-
          arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python37-SciPy1x:22
      ReservedConcurrentExecutions: 10
